[book]
authors = ["zhouyu3"]
language = "en"
src = "src"
title = "KnowBank"
description = "Advanced Knowledge Bank with Custom Theme"

[build]
create-missing = true

[output.html]
# Theme configuration
default-theme = "light"
preferred-dark-theme = "navy"
theme = "theme"
site-url = "/"
cname = "localhost"

# Advanced HTML features
smart-punctuation = true
mathjax-support = true
copy-fonts = true

# Print support
print-enable = true

# Custom styling
# additional-css = ["css/custom.css"]
# additional-js = ["js/custom.js"]

# Search configuration
[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
